// Fake chrome.* for previewing the popup outside the extension.
// Loaded by popup-preview.html (generated by tools/render-store-images.sh from extension/popup/popup.html).
// ?mode=on|off|confirm|disabled|empty|expanded|clearconfirm|hover  &lang=en|zh_CN
const params = new URLSearchParams(location.search);
const mode = params.get("mode") || "on";
const lang = params.get("lang") || "zh_CN";
const xhr = new XMLHttpRequest();
xhr.open("GET", `../../extension/_locales/${lang}/messages.json`, false);
xhr.send();
const messages = JSON.parse(xhr.responseText);
function get_message(key, subs = []) {
    const m = messages[key];
    if (!m) return "";
    return m.message.replace(/\$([A-Za-z_]+)\$/g, (_, name) => {
        const content = m.placeholders?.[name.toLowerCase()]?.content ?? "";
        return content.replace(/\$(\d)/g, (__, i) => subs[Number(i) - 1] ?? "");
    });
}
const host = "www.example-novel.com";
const enabled = mode !== "off" && mode !== "confirm";
const bm = (id, path, title) => ({ id, url: `https://${host}${path}`, title });
const bookmarks = mode === "confirm"
    ? [bm("a", "/book/1/3.html", "a"), bm("b", "/book/2/9.html", "b"), bm("c", "/book/3/1.html", "c")]
    : [bm("a", "/book/123/13.html", "a")];
const MIN = 60 * 1000;
let trash = mode === "empty" ? [] : [
    { id: "1", title: "第十二章 风起云涌 - 示例小说网", url: `https://${host}/book/123/12.html`, removed_at: Date.now() - 20 * 1000 },
    { id: "2", title: "第十一章 夜雨 - 示例小说网", url: `https://${host}/book/123/11.html`, removed_at: Date.now() - 35 * MIN },
    { id: "3", title: "第十章 山门 - 示例小说网", url: `https://${host}/book/123/10.html`, removed_at: Date.now() - 3 * 24 * 60 * MIN },
];
if (lang === "en") {
    const en_titles = ["Chapter 12: The Storm Rises - Example Novels", "Chapter 11: Night Rain - Example Novels", "Chapter 10: The Mountain Gate - Example Novels"];
    trash.forEach((t, i) => (t.title = en_titles[i]));
}
window.chrome = {
    i18n: { getMessage: get_message, getUILanguage: () => lang.replace("_", "-") },
    tabs: { query: async () => [{ url: mode === "disabled" ? "chrome://newtab/" : `https://${host}/book/123/13.html` }] },
    storage: { local: {
        get: async k => k === "enabled_sites" ? { enabled_sites: enabled ? { [host]: 1 } : {} } : k === "trash" ? { trash } : {},
        set: async () => {},
    }},
    bookmarks: { getTree: async () => [{ id: "0", children: [{ id: "1", children: bookmarks }] }] },
    runtime: { sendMessage: async m => {
        if (m.type === "clear") trash = [];
        if (m.type === "discard" || m.type === "restore") trash = trash.filter(t => t.id !== m.id);
        return { ok: true };
    }},
};
// screenshots must not catch mid-animation frames
const no_anim = document.createElement("style");
no_anim.textContent = "*, *::before, *::after { transition: none !important; }";
document.head.append(no_anim);
// report rendered height to the store template (works across file:// origins)
setTimeout(() => {
    try {
        // hello.html has no doctype (quirks mode): body stretches to the viewport, so measure content instead
        const bottom = Math.max(...[...document.body.children].map(el => el.getBoundingClientRect().bottom));
        parent.postMessage({ popup_height: Math.ceil(bottom) + 14 }, "*");
    } catch (e) {
        parent.postMessage({ error: String(e) }, "*");
    }
}, 500);
const click = sel => document.querySelector(sel).click();
setTimeout(() => {
    if (mode === "confirm") click("#btn");
    if (["expanded", "clearconfirm", "hover", "empty"].includes(mode)) click("#trash-toggle");
    if (mode === "clearconfirm") click("#trash-clear");
    if (mode === "hover") {
        const s = document.createElement("style");
        s.textContent = "#trash li:first-child { background-color: var(--hover); } #trash li:first-child .btn-discard { opacity: 1; }";
        document.head.append(s);
    }
}, 300);
